# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55c1349176dbcaae8c1097b5ac978a1a7c65e6edf1f0be2fc1b7dbce85263c16c463ea68011d1f94383bad28ab38a9ae89b11e6d567c572b9549070c9ddf37b7
  telegram:
    bot:
      token: <%= ENV['TELEGRAM_BOT_API_TOKEN'] %>
      username: <%= ENV['TELEGRAM_BOT_NAME'] %>
test:
  secret_key_base: 5b235e0f6e290af7249ba576f718a68c1a82a06460cf9287d2a8a2fa22eafce2d9631e0deddbd9f4e5d3a0254cb1c8f4f008ed0b26ca3b59423d66019455272e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
